### ISSUE TITLE
GIT_VERSION and PACKAGE_VERSION

### ISSUE THREAD

**Issue by samuelschuettler** [UMEssen/Body-and-Organ-Analysis#15]
Hi there, 

i've used the README for the env and docker-compose file. 

When running `docker compose up` i get the following warnings:
```
WARN[0000] The "GIT_VERSION" variable is not set. Defaulting to a blank string. 
WARN[0000] The "PACKAGE_VERSION" variable is not set. Defaulting to a blank string. 
WARN[0000] The "GIT_VERSION" variable is not set. Defaulting to a blank string. 
WARN[0000] The "PACKAGE_VERSION" variable is not set. Defaulting to a blank string. 
WARN[0000] The "GIT_VERSION" variable is not set. Defaulting to a blank string. 
WARN[0000] The "PACKAGE_VERSION" variable is not set. Defaulting to a blank string.
```
Should i add `GIT_VERSION` and `PACKAGE_VERSION` to something in the env file and if yes what?

Cheers
Samuel from UKE Hamburg

**Comment by giuliabaldini** [comment]
Hi there!

just run the following script before `docker compose up`:
```
source scripts/generate_version.sh
```
It is however not incredibly important. If you have downloaded the images from docker hub, the variables are already set, and if you are building it from scratch, it is not incredibly important if they are missing. It is just such that if there are any problems, we can always know with which version of the tool was run, but it does not influence its functionality!

Let me know if there are any problems!

Best,
Giulia

**Comment by giuliabaldini** [comment]
oh, and please use 
```bash
docker compose up orthanc rabbitmq worker-gpu -d
```
instead of docker-compose up, otherwise the Triton version of the tool will also be started!

**Comment by samuelschuettler** [comment]
A thank you for the explanations. Everything seems to be working properly :+1:
