### ISSUE TITLE
Dicom Tags in "get_dicom_tags" appear to be empty

### ISSUE THREAD

**Issue by eFroD** [UMEssen/Body-and-Organ-Analysis#29]
Hello there! 

When using the BOA PACS deployment, I observed that the output hierarchy is `OUTPUT/ae_title/__/x_`
instead of the `StudyDate_AccessionNumber_StudyDescription`  and the corresponding tags for the series.

It seems to have trouble at the get_dicom_tags function. I this a known issue or a problem at my end?

**Comment by giuliabaldini** [comment]
Hi there!

We are actually not aware of this problem. Have you checked out the DICOM tags of your studies? Are they just set to an empty string or are they well-defined?

Best,
Giulia

**Comment by eFroD** [comment]
Just found the problem, it was indeed on my end... Than you very much!
