### ISSUE TITLE
Prerequisites for running the application

### ISSUE THREAD

**Issue by Negar-Shah** [UMEssen/Body-and-Organ-Analysis#33]
Hi everyone,

Thank you for the amazing toolkit. I wanted to ask what are the prerequisites for running the application? Which Docker version, Nvidia driver version, and other toolkits are used?

Best regards,
Negar

**Comment by JannisStraus** [comment]
Hi Negar,

We run BOA on Ubuntu 22.04.4 LTS with Nvidia Driver version 525.147.05, CUDA version 12.0 and Docker version 25.0.3. The Nvidia Driver and CUDA versions primary depend on the GPUs you are using. We use a GPU Cluster with multiple GPUs so you may need different versions. You can find the correct Nvidia Driver on https://www.nvidia.com/Download/index.aspx?lang=en-us and the compatible CUDA version on https://developer.nvidia.com/cuda-toolkit-archive. I hope that I could help you.

Best regards,
Jannis

**Comment by Negar-Shah** [comment]
Thank you Jannis for your fast reply.
 I am now encountering another issue, for which I will create a new ticket.

Best regards,
Negar
